### ISSUE TITLE
[D3 get started]

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#3]
- [x] Create d3 `map of contents` page in obsidian 
- [x] build something in D3 based on video watched + document on obsidian zettle  (#2)
- [x] @ran-codes find something on observable to fork and learn/copy/edit: https://observablehq.com/collection/@mahog/davi-d3-tutorial
- [x] @anujtanwar98  fork it and reproduce/make-some-edit  + document on obsidian zettle (#2)
- [ ] @ran-codes build a d3 map  ([ex1](https://observablehq.com/@d3/u-s-map), [ex2](https://observablehq.com/@d3/hexbin-map))

## D3 Svelte components page

-  [x] for each chart. I want some text under neeath. containing notes of what are the 'new' d3 things you learn while putting.
-  [x] modify chart4 in chart4b   
   - [x] add tooltip that shows x and y values
   - [x] i want each dot to have a different color mapped to group. group 1= red, group 2 = blue.
   - [x] refactor or semantic d3-variables
   - [x] fix typescript bug
- [x] start on chart3b
   - [x] tooltip
   - [x] chart title  
   - [x] add dots for each data point
   - [x] extra: log scale the y-axis
   - [x] extra: can you smooth the line?

**Comment by anujtanwar98** [comment]
[barChart Example](https://github.com/Drexel-UHC/interactivity/tree/main/d3%20showcase)
this is the example i did based on the video

**Comment by ran-codes** [comment]
congrats!! first D3 viz!! One minor request in general, always deploy to web and share there. (also its good to check your app/scrolly can be hosted on the cloud). 

Can you deploy this to a static site host so we can review tomorrow. (i would use just [netlify](https://www.netlify.com/?utm_source=google&utm_medium=paid_search&utm_campaign=12755510784&adgroup=118788138897&utm_term=netlify&utm_content=aud-951962601255:kwd-309804753741&creative=514583565825&device=c&matchtype=b&location=9007317&gclid=Cj0KCQjw8qmhBhClARIsANAtbocjeONiQVwKkOl8JtttH6yGklJCSvvL3GMY6tZBd62O9jvxmH96crYaAgSuEALw_wcB) for now). they have a easy to deploy click and drag your public/ folder and deploy as static site. for example here is temp one: https://idyllic-toffee-d1273b.netlify.app/ using their [public drop and deploy demo feature](https://app.netlify.com/drop/). But if oyu sign up its free to host unlimited static sites.

To do:
- [ ] sign up for a free netlify account
- [ ] deploy your /d3 showcase 

then you can run through the code and results tomorrow.

**Comment by anujtanwar98** [comment]
[This is the live link](https://ornate-heliotrope-811a71.netlify.app/)

**Comment by ran-codes** [comment]
maybe have a zettle to jot down your thoughts through this tutorial series would be nice.
